services: docker

env:
  - MONGO_INITDB_ROOT_USERNAME=example
  - MONGO_INITDB_ROOT_PASSWORD=example
  - MONGO_INITDB_DATABASE=api
  - MONGO_DATA_DIR=/data/db
  - MONGO_TEST_DATA_DIR=/data/test_db
  - MONGO_LOG_FILE=/mongodb/mongodb.log
  - PORT=80

before_install:
  - docker -v
  - sudo /etc/init.d/postgresql stop
  - sudo service mysql stop
  - docker build -t vc/backend-test -f ./docker/Dockerfile.dev ./backend-test

after_success:
  - docker build -t vc/backend-test ./backend-test
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push vc/backend-test

install:
  - npm run test

script:
  - docker run vc/backend-test npm test -- --coverage